comments:
  active: 'giscus' # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # Giscus options › https://giscus.app
  giscus:
    repo: "pmaarks/pmaarks.github.io" # <gh-username>/<repo>
    repo_id: "R_kgDOMZNtdA"
    category: "Comments"
    category_id: "DIC_kwDOMZNtdM4ChMSi"
    mapping: # optional, default to 'pathname'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`


# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM